export const FORBIDDEN = "FORBIDDEN";
export const NOT_FOUND = "NOT_FOUND";
export const INCORRECT_PASSWORD = "INCORRECT_PASSWORD";
export const ROOM_FULL = "ROOM_FULL";
export const UNAUTHORIZED = "UNAUTHORIZED";
